version: "3.9"

services:
  backend:
    env_file:
      - .env.production
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

  worker:
    env_file:
      - .env.production
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

  mongodb:
    ports: []
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

  redis:
    ports: []
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
